# Generated by Django 2.2.1 on 2020-05-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debits_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpurchase',
            name='subscription_reference',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
